### ISSUE TITLE
Test with different connection pool implementation

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-web-service-docker#3]
```
    compile (group: 'ch.ehi.oereb', name: 'oereb-web-service', version: "0.9.+", changing: true) {
        exclude group: 'com.zaxxer', module: 'HikariCP'
    }
    implementation 'org.apache.tomcat:tomcat-jdbc:9.0.10'
```

Sind die Connection Timeouts nicht verhinderbar? Oder ist das anders bei anderen Implementierungen und abhängig von den Einstellungen? Ich verstehe das Verhalten noch nicht so ganz:

Es kommen viele Anfragen. Eine Anfrage (xml only, kein pdf) wird super schnell abgehandelt. Warum gibt es trotzdem eine 30s-Connection-Timeout des Connection Pool ggü der DB? Wird die Connection nach dem Abarbeiten nicht sofort in den Pool zurück geliefert?

Lokal mit einem sehr ähnlichen Service und ähnlicher Architektur habe ich das nicht.

**Comment by claeis** [comment]
M.E. versucht ein Connection Pool die Verbindung zur DB so lange wie möglich offen zu halten, um sich den Aufwand für das Öffnen zu sparen.
 
Und die DB versucht, die Verbindung so früh wie möglich zu schliessen, um nicht länger als nötig angreifbar zu sein.

Um die Anzahl solcher Warnings zu reduzieren, musst Du also die beiden besser aufeinander abstimmen...
